name: Scraping Automation

on:
  schedule:
    - cron: '0 0 */2 * *'  # Exécute le workflow tous les 2 jours à minuit UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraping script
        run: python main.py

      - name: Commit and push changes
        run: |
          git config --global user.name "Elmahjoub-bentaher"
          git config --global user.email "elmahjoub.bentaher@edu.uiz.ac.ma"
          git add .
          git commit -m "Add new scraped data" || echo "No changes to commit"
          git push origin main
